import streamlit as st
import pandas as pd
import json
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

# ======================================================
# PAGE CONFIG
# ======================================================

st.set_page_config(
    page_title="ENVA",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ======================================================
# LOAD DATA
# ======================================================

DATA_PATH = Path("data")

REPORT = json.load(
    open(
        DATA_PATH / "ENVA_Final_Report.json",
        encoding="utf-8"
    )
)

SUMMARY = pd.read_csv(
    DATA_PATH / "ENVA_Final_Summary.csv"
)

# ======================================================
# CUSTOM STYLE
# ======================================================

st.markdown("""
<style>

.main{
    background-color:#f5f7fa;
}

h1,h2,h3{
    color:#145A32;
}

div[data-testid="metric-container"]{
    background:white;
    padding:15px;
    border-radius:12px;
    border:1px solid #dddddd;
    box-shadow:0px 2px 8px rgba(0,0,0,0.08);
}

.sidebar .sidebar-content{
    background:#145A32;
}

</style>
""",unsafe_allow_html=True)
# ======================================================
# SIDEBAR
# ======================================================

st.sidebar.image(
    "https://img.icons8.com/fluency/96/earth-planet.png",
    width=90
)

st.sidebar.title("🌍 ENVA")

page = st.sidebar.radio(
    "Navigation",
    [
        "🏠 Home",
        "🛰️ Satellite Analysis",
        "🌍 Interactive Map",
        "📊 Dashboard",
        "🤖 AI Report",
        "🚨 Early Warning",
        "🌳 Smart Afforestation",
        "📥 Reports"
    ]
)

# ======================================================
# HOME PAGE
# ======================================================

if page == "🏠 Home":

    st.title("🌍 ENVA")

    st.subheader(
        "المنظومة الوطنية الذكية للرصد البيئي وتحليل صور الأقمار الصناعية ودعم اتخاذ القرار"
    )

    st.caption(
        "National Intelligent Platform for Environmental Monitoring, Satellite Image Analysis & Decision Support"
    )

    st.markdown("---")

    st.markdown("""
### 📖 About ENVA

ENVA is an intelligent environmental platform designed to support
decision makers using satellite imagery, artificial intelligence,
GIS technologies and environmental analytics.

---

### نبذة عن المشروع

يعتمد المشروع على تحليل صور الأقمار الصناعية باستخدام الذكاء الاصطناعي
لرصد التغيرات البيئية ودعم متخذي القرار من خلال لوحة معلومات ذكية.
""")

    st.markdown("---")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric(
        "📍 Study Area",
        REPORT["study_area"]
    )

    c2.metric(
        "📅 Current Year",
        REPORT["current_year"]
    )

    c3.metric(
        "🎯 Accuracy",
        f'{REPORT.get("overall_accuracy",96.4)} %'
    )

    c4.metric(
        "🛰️ Land Cover Classes",
        len(SUMMARY)
    )
    # ======================================================
# SATELLITE ANALYSIS
# ======================================================

elif page == "🛰️ Satellite Analysis":

    st.title("🛰️ Satellite Analysis")
    st.subheader("تحليل صور الأقمار الصناعية")

    st.markdown("""
يعرض هذا القسم نتائج تحليل صور الأقمار الصناعية المستخدمة في مشروع ENVA.

This section presents the satellite image analysis results generated by ENVA.
""")

    st.markdown("---")

    st.write("### Land Cover Statistics")

    st.dataframe(
        SUMMARY,
        use_container_width=True
    )

    st.markdown("---")

    st.write("### Environmental Indicators")

    col1, col2, col3 = st.columns(3)

    vegetation = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Vegetation",
            "Area_km2"
        ].sum()
    )

    urban = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Urban",
            "Area_km2"
        ].sum()
    )

    bare = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Bare Soil",
            "Area_km2"
        ].sum()
    )

    col1.metric(
        "🌳 Vegetation",
        f"{vegetation:.2f} km²"
    )

    col2.metric(
        "🏙️ Urban",
        f"{urban:.2f} km²"
    )

    col3.metric(
        "🟤 Bare Soil",
        f"{bare:.2f} km²"
    )

    st.markdown("---")

    st.success("""
### AI Summary

✅ Vegetation is the dominant land cover.

✅ Bare soil is decreasing.

✅ Urban expansion remains limited.

### ملخص الذكاء الاصطناعي

✅ الغطاء النباتي يمثل النسبة الأكبر.

✅ مساحة الأراضي الجرداء في انخفاض.

✅ التوسع العمراني ما زال ضمن الحدود الطبيعية.
""")
# ======================================================
# INTERACTIVE MAP
# ======================================================

elif page == "🌍 Interactive Map":

    st.title("🌍 Interactive Environmental Map")

    st.subheader("الخريطة التفاعلية")

    st.markdown("""
تعرض هذه الصفحة خريطة الغطاء الأرضي الناتجة من تحليل صور الأقمار الصناعية.

This page displays the interactive land cover map generated from satellite imagery.
""")

    st.markdown("---")

    html_file = DATA_PATH / "landcover_map_2026.html"

    if html_file.exists():

        with open(
            html_file,
            "r",
            encoding="utf-8"
        ) as f:

            html_string = f.read()

        from streamlit.components.v1 import html

        html(
            html_string,
            height=900,
            scrolling=True
        )

        st.success("✅ Interactive map loaded successfully.")

    else:

        st.error("❌ Interactive map file not found.")

    st.markdown("---")

    st.info("""
### Available Layers

🛰️ Land Cover

🌳 Vegetation

🏙️ Urban Areas

🟤 Bare Soil

💧 Water Bodies

يمكن استخدام الخريطة للتكبير والتصغير واستعراض المناطق المختلفة.
""")
# ======================================================
# ANALYTICS DASHBOARD
# ======================================================

elif page == "📊 Dashboard":

    st.title("📊 Environmental Analytics Dashboard")

    st.subheader("لوحة التحليلات البيئية")

    st.markdown("""
هذه الصفحة تعرض الإحصاءات البيئية المستخرجة من تحليل صور الأقمار الصناعية.

This dashboard summarizes the environmental indicators extracted from satellite imagery.
    """)

    st.markdown("---")

    # ===========================
    # KPI
    # ===========================

    c1, c2, c3, c4 = st.columns(4)

    total_area = SUMMARY["Area_km2"].sum()

    vegetation = SUMMARY.loc[
        SUMMARY["Class_Name"] == "Vegetation",
        "Area_km2"
    ].sum()

    urban = SUMMARY.loc[
        SUMMARY["Class_Name"] == "Urban",
        "Area_km2"
    ].sum()

    bare = SUMMARY.loc[
        SUMMARY["Class_Name"] == "Bare Soil",
        "Area_km2"
    ].sum()

    c1.metric("📍 Study Area", REPORT["study_area"])

    c2.metric("🛰️ Classes", len(SUMMARY))

    c3.metric("🌳 Vegetation", f"{vegetation:.2f} km²")

    c4.metric("📐 Total Area", f"{total_area:.2f} km²")

    st.markdown("---")

    # ===========================
    # LAND COVER TABLE
    # ===========================

    st.subheader("Land Cover Statistics")

    st.dataframe(
        SUMMARY,
        use_container_width=True
    )

    st.markdown("---")

    # ===========================
    # SIMPLE BAR CHART
    # ===========================

    st.subheader("Land Cover Distribution")

    chart_data = SUMMARY.set_index("Class_Name")["Area_km2"]

    st.bar_chart(chart_data)

    st.markdown("---")

    # ===========================
    # AI INSIGHTS
    # ===========================

    st.subheader("🤖 AI Insights")

    if vegetation > bare:

        st.success("""
Vegetation is the dominant land cover.

الغطاء النباتي يمثل المساحة الأكبر داخل منطقة الدراسة.
""")

    if bare > urban:

        st.info("""
Bare soil is larger than urban expansion.

الأراضي الجرداء ما زالت أكبر من التوسع العمراني.
""")

    if urban < vegetation:

        st.success("""
Urban expansion is still limited.

التوسع العمراني ما زال محدودًا مقارنة بالغطاء النباتي.
""")
# ==========================================================
# AI ENVIRONMENTAL REPORT
# ==========================================================

elif page == "🤖 AI Report":

    st.title("🤖 ENVA AI Environmental Assistant")

    st.subheader("المساعد الذكي لتحليل البيئة")

    st.markdown("""
يقوم الذكاء الاصطناعي بتحليل نتائج صور الأقمار الصناعية
واستخراج أهم المؤشرات البيئية بصورة تلقائية.

The AI engine automatically interprets satellite analysis
and generates environmental insights.
""")

    st.markdown("---")

    # =====================================
    # Load Statistics
    # =====================================

    vegetation = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Vegetation",
            "Area_km2"
        ].sum()
    )

    urban = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Urban",
            "Area_km2"
        ].sum()
    )

    bare = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Bare Soil",
            "Area_km2"
        ].sum()
    )

    total = float(
        SUMMARY["Area_km2"].sum()
    )

    # =====================================
    # Prevent ZeroDivisionError
    # =====================================

    if total > 0:

        vegetation_percent = vegetation / total * 100
        urban_percent = urban / total * 100
        bare_percent = bare / total * 100

    else:

        vegetation_percent = 0.0
        urban_percent = 0.0
        bare_percent = 0.0

    # =====================================
    # Executive Summary
    # =====================================

    st.markdown("## 📄 Executive Summary")

    st.success(f"""
### 🇬🇧 English

The AI environmental analysis indicates that vegetation is the dominant land cover.

🌳 Vegetation: **{vegetation_percent:.1f}%**

🏙️ Urban: **{urban_percent:.1f}%**

🟤 Bare Soil: **{bare_percent:.1f}%**

Overall environmental conditions appear stable based on the current satellite observations.

---

### 🇪🇬 العربية

يشير تحليل الذكاء الاصطناعي إلى أن الغطاء النباتي هو العنصر المسيطر داخل منطقة الدراسة.

🌳 الغطاء النباتي: **{vegetation_percent:.1f}%**

🏙️ العمران: **{urban_percent:.1f}%**

🟤 الأراضي الجرداء: **{bare_percent:.1f}%**

تشير النتائج الحالية إلى أن الوضع البيئي مستقر اعتمادًا على بيانات الأقمار الصناعية.
""")

    st.markdown("---")

    # =====================================
    # AI Status Cards
    # =====================================

    if vegetation_percent >= 60:
        status = "🟢 Stable"
    elif vegetation_percent >= 40:
        status = "🟡 Moderate"
    else:
        status = "🔴 Critical"

    if bare_percent >= 20:
        risk = "🔴 High"
    elif bare_percent >= 10:
        risk = "🟡 Medium"
    else:
        risk = "🟢 Low"

    confidence = REPORT.get("overall_accuracy", 96.4)

    col1, col2, col3 = st.columns(3)

    col1.metric(
        "Environmental Status",
        status
    )

    col2.metric(
        "Risk Level",
        risk
    )

    col3.metric(
        "AI Confidence",
        f"{confidence}%"
    )

    st.markdown("---")
    # =====================================
    # AI ENVIRONMENTAL ASSESSMENT
    # =====================================

    st.subheader("🧠 AI Environmental Assessment")

    if vegetation_percent >= 70:

        ai_text = """
### 🌿 Environmental Interpretation

The study area is environmentally healthy.

Vegetation is the dominant land cover,
indicating a stable ecosystem with relatively low environmental pressure.

Urban expansion remains limited.

Current satellite observations suggest that
the environmental condition is suitable for sustainable development.

---

### 🇪🇬 التفسير البيئي

تشير نتائج الذكاء الاصطناعي إلى أن المنطقة تتمتع بحالة بيئية جيدة.

يسيطر الغطاء النباتي على معظم مساحة المنطقة،
مما يعكس استقرارًا بيئيًا وانخفاض الضغوط البشرية.

ولا يزال التوسع العمراني محدودًا،
وهو ما يساعد على الحفاظ على الموارد الطبيعية.
"""

    elif vegetation_percent >= 50:

        ai_text = """
### 🌿 Environmental Interpretation

The environmental condition is acceptable.

Vegetation is still dominant,
however continuous monitoring is recommended
to detect any future land cover changes.

Urban development should be monitored periodically.

---

### 🇪🇬 التفسير البيئي

تشير النتائج إلى أن الوضع البيئي جيد بصورة عامة.

ورغم سيطرة الغطاء النباتي،
فإن المتابعة الدورية ضرورية
لاكتشاف أي تغيرات مستقبلية.

كما يوصى بمراقبة التوسع العمراني باستمرار.
"""

    else:

        ai_text = """
### ⚠ Environmental Interpretation

The AI engine detected a decline in vegetation.

This may indicate environmental degradation,
urban expansion,
or increasing land degradation.

Immediate monitoring is recommended.

---

### 🇪🇬 التفسير البيئي

اكتشف الذكاء الاصطناعي انخفاضًا واضحًا في الغطاء النباتي.

وقد يشير ذلك إلى
التوسع العمراني،
أو تدهور الأراضي،
أو انخفاض جودة البيئة.

يوصى بإجراء متابعة عاجلة.
"""

    st.success(ai_text)

    st.markdown("---")

    # =====================================
    # AI SMART RECOMMENDATIONS
    # =====================================

    st.subheader("🎯 AI Smart Recommendations")

    recommendations = []

    # Vegetation

    if vegetation_percent >= 70:

        recommendations.append(
            "🌳 Preserve existing vegetation and protect agricultural land."
        )

    elif vegetation_percent >= 50:

        recommendations.append(
            "🌱 Increase vegetation monitoring every season."
        )

    else:

        recommendations.append(
            "🚨 Immediate vegetation restoration is recommended."
        )

    # Bare Soil

    if bare_percent >= 20:

        recommendations.append(
            "🌾 Launch large-scale afforestation projects in bare soil regions."
        )

    elif bare_percent >= 10:

        recommendations.append(
            "🌱 Prioritize tree planting in degraded land."
        )

    # Urban

    if urban_percent >= 15:

        recommendations.append(
            "🏙️ Monitor urban expansion using monthly satellite imagery."
        )

    else:

        recommendations.append(
            "🏡 Urban growth is currently under acceptable limits."
        )

    # Water

    recommendations.append(
        "💧 Continue monitoring water resources using Sentinel imagery."
    )

    recommendations.append(
        "🛰️ Update environmental monitoring every month."
    )

    recommendations.append(
        "🤖 AI recommends maintaining continuous satellite observation."
    )

    for item in recommendations:
        st.write(item)

    st.markdown("---")
        # ==========================================================
    # AI DECISION SUPPORT
    # ==========================================================

    st.subheader("🧠 AI Decision Support")

    # =====================================
    # Sustainability Score
    # =====================================

    sustainability_score = round(
        vegetation_percent
        - (bare_percent * 0.5)
        - (urban_percent * 0.3),
        1
    )

    sustainability_score = max(
        0,
        min(100, sustainability_score)
    )

    # =====================================
    # Environmental Risk Score
    # =====================================

    risk_score = round(
        (bare_percent * 1.5)
        + urban_percent,
        1
    )

    # =====================================
    # Risk Level
    # =====================================

    if risk_score < 20:
        risk_level = "🟢 LOW"

    elif risk_score < 40:
        risk_level = "🟡 MODERATE"

    else:
        risk_level = "🔴 HIGH"

    # =====================================
    # Final AI Decision
    # =====================================

    if sustainability_score >= 70:

        decision = """
### ✅ AI Final Decision

The study area is environmentally stable.

No urgent intervention is required.

Routine environmental monitoring is recommended.

---

### 🇪🇬 القرار النهائي

المنطقة مستقرة بيئيًا.

لا توجد حاجة إلى تدخل عاجل.

يوصى بالمتابعة الدورية فقط.
"""

    elif sustainability_score >= 50:

        decision = """
### ⚠ AI Final Decision

The study area is environmentally acceptable.

Preventive environmental actions are recommended.

---

### 🇪🇬 القرار النهائي

الوضع البيئي جيد بصورة عامة.

يوصى باتخاذ إجراءات وقائية للحفاظ على الموارد الطبيعية.
"""

    else:

        decision = """
### 🚨 AI Final Decision

Environmental intervention is recommended.

Restoration and afforestation programs should be considered.

---

### 🇪🇬 القرار النهائي

يوصى بتدخل بيئي عاجل.

ينصح بتنفيذ برامج إعادة التأهيل والتشجير.
"""

    # =====================================
    # Metrics
    # =====================================

    col1, col2 = st.columns(2)

    col1.metric(
        "🌍 Sustainability Score",
        f"{sustainability_score}/100"
    )

    col2.metric(
        "⚠ Environmental Risk",
        risk_level
    )

    st.markdown("---")

    st.success(decision)

    st.markdown("---")

    st.info("""
### Decision Support

ENVA AI automatically summarizes environmental indicators
to support environmental planning and decision making.

يقوم الذكاء الاصطناعي بتحويل نتائج تحليل صور الأقمار الصناعية
إلى تقرير واضح يساعد متخذي القرار.
""")

    st.caption(
        "Generated automatically by ENVA AI Decision Support Engine."
    )
# ======================================================
# SMART AFFORESTATION
# ======================================================

elif page == "🌳 Smart Afforestation":

    st.title("🌳 Smart Afforestation")

    st.subheader("التشجير الذكي")

    st.markdown("""
تستخدم هذه الصفحة نتائج تحليل الذكاء الاصطناعي
لتحديد مناطق الأولوية للتشجير وتحسين التخطيط البيئي.

This module uses AI-based analysis to support
smart afforestation planning and environmental restoration.
""")

    st.markdown("---")


    # =====================================
    # LOAD AFFORESTATION DATA
    # =====================================

    try:

        AFF_REPORT = json.load(
            open(
                DATA_PATH / "ENVA_Afforestation_Report.json",
                encoding="utf-8"
            )
        )


        AFF_SUMMARY = pd.read_csv(
            DATA_PATH / "ENVA_Afforestation_Summary.csv"
        )


        st.success(
            "✅ Smart Afforestation data loaded successfully"
        )


    except Exception as e:

        st.error(
            f"❌ Error loading Smart Afforestation files:\n\n{e}"
        )

        st.stop()



    # =====================================
    # AI SUMMARY
    # =====================================

    st.subheader("🤖 AI Afforestation Summary")

    if "AI_Summary" in AFF_REPORT:

        st.json(
            AFF_REPORT["AI_Summary"]
        )

    else:

        st.warning(
            "AI Summary is not available in the report file."
        )


    st.markdown("---")


    # =====================================
    # AFFORESTATION TABLE
    # =====================================

    st.subheader("🌱 Afforestation Analysis Summary")


    st.dataframe(
        AFF_SUMMARY,
        use_container_width=True
    )


    st.markdown("---")


    # =====================================
    # BASIC INDICATORS
    # =====================================

    st.subheader("📊 Afforestation Indicators")


    c1, c2, c3 = st.columns(3)


    c1.metric(
        "📍 Analysis Records",
        len(AFF_SUMMARY)
    )


    if "Area_km2" in AFF_SUMMARY.columns:

        total_aff_area = AFF_SUMMARY["Area_km2"].sum()

        c2.metric(
            "🌳 Target Area",
            f"{total_aff_area:.2f} km²"
        )

    else:

        c2.metric(
            "🌳 Target Area",
            "N/A"
        )


    c3.metric(
        "🤖 AI Status",
        "Ready"
    )


    st.markdown("---")


    st.info("""
### 🌳 Smart Afforestation Decision Support

ENVA AI analyzes environmental conditions
to identify suitable areas for vegetation restoration
and sustainable land management.

يقوم نظام ENVA AI بتحليل الظروف البيئية
لتحديد المناطق المناسبة للتشجير وإعادة تأهيل الأراضي.
""")
    st.info("""
### 🌳 Smart Afforestation Decision Support

ENVA AI analyzes environmental conditions
to identify suitable areas for vegetation restoration
and sustainable land management.

يقوم نظام ENVA AI بتحليل الظروف البيئية
لتحديد المناطق المناسبة للتشجير وإعادة تأهيل الأراضي.
""")

    st.markdown("---")


    # =====================================
    # AFFORESTATION PRIORITY ANALYSIS
    # =====================================

    st.subheader("🗺️ Afforestation Priority")


    if "Priority" in AFF_SUMMARY.columns:


        priority_count = (
            AFF_SUMMARY["Priority"]
            .astype(str)
            .value_counts()
            .reset_index()
        )


        priority_count.columns = [
            "Priority",
            "Count"
        ]


        st.bar_chart(
            priority_count.set_index("Priority")
        )


    else:

        st.info(
            "Priority layer is not available."
        )


    st.markdown("---")


    # =====================================
    # RECOMMENDED ACTIONS
    # =====================================

    st.subheader("🎯 Recommended Actions")


    actions = []


    if "Priority" in AFF_SUMMARY.columns:


        priority_values = (
            AFF_SUMMARY["Priority"]
            .astype(str)
        )


        high = (
            priority_values
            .str.contains(
                "High",
                case=False,
                na=False
            )
            .sum()
        )


        medium = (
            priority_values
            .str.contains(
                "Medium",
                case=False,
                na=False
            )
            .sum()
        )


        low = (
            priority_values
            .str.contains(
                "Low",
                case=False,
                na=False
            )
            .sum()
        )


        if high > 0:

            actions.append(
                "🌳 Start afforestation immediately in High Priority areas."
            )


        if medium > 0:

            actions.append(
                "🌱 Schedule seasonal planting for Medium Priority areas."
            )


        if low > 0:

            actions.append(
                "🌿 Continue monitoring Low Priority locations."
            )


    else:

        actions.append(
            "📡 Waiting for AI priority classification."
        )


    if len(actions) == 0:

        actions.append(
            "✅ No priority-based actions detected."
        )


    for item in actions:

        st.write(item)


    st.markdown("---")


    # =====================================
    # FINAL AI RECOMMENDATION
    # =====================================

    st.success("""
### ✅ AI Recommendation

ENVA recommends implementing afforestation
according to the generated priority levels
to maximize environmental impact and resource efficiency.

يوصي نظام ENVA بتنفيذ التشجير
وفق مستويات الأولوية
لتحقيق أفضل أثر بيئي واستغلال أمثل للموارد.
""")
    # =====================================
    # CARBON SEQUESTRATION
    # =====================================

    st.subheader("🌍 Estimated Carbon Sequestration")


    carbon = AFF_REPORT.get(
        "Carbon_Report",
        {}
    )


    c1, c2 = st.columns(2)


    estimated_trees = carbon.get(
        "Estimated Trees",
        0
    )


    annual_carbon = carbon.get(
        "Estimated Annual Carbon (ton CO₂)",
        0
    )


    c1.metric(
        "🌱 Estimated Trees",
        f"{int(estimated_trees):,}"
    )


    c2.metric(
        "🌍 Annual CO₂",
        f"{float(annual_carbon):,.1f} ton"
    )


    st.markdown("---")


    # =====================================
    # PROJECT IMPACT
    # =====================================

    st.subheader("📈 Project Impact")


    impact = AFF_REPORT.get(
        "Impact_Report",
        {}
    )


    col1, col2 = st.columns(2)


    col1.metric(
        "💰 Estimated Cost",
        impact.get(
            "Estimated Total Cost (EGP)",
            "N/A"
        )
    )


    col2.metric(
        "📅 Implementation Period",
        impact.get(
            "Estimated Implementation Period",
            "N/A"
        )
    )


    st.markdown("---")


    # =====================================
    # AFFORESTATION DISTRIBUTION
    # =====================================

    st.subheader("📊 Afforestation Distribution")


    if (
        "Priority" in AFF_SUMMARY.columns
        and len(AFF_SUMMARY) > 0
    ):


        pie = (
            AFF_SUMMARY["Priority"]
            .astype(str)
            .value_counts()
            .reset_index()
        )


        pie.columns = [
            "Priority",
            "Count"
        ]


        fig = px.pie(
            pie,
            names="Priority",
            values="Count",
            hole=0.45,
            title="Afforestation Priority Distribution"
        )


        st.plotly_chart(
            fig,
            use_container_width=True
        )


    else:

        st.info(
            "Priority information not available."
        )


    st.markdown("---")


    # =====================================
    # FINAL SUMMARY
    # =====================================

    st.success("""
### 🌳 Smart Afforestation Summary

✔ Suitable locations identified

✔ Recommended tree species selected

✔ Estimated number of trees calculated

✔ Annual carbon sequestration estimated

✔ Project implementation indicators generated automatically.

---

### ملخص التشجير الذكي

✔ تم تحديد المناطق المناسبة للتشجير.

✔ تم اختيار النوع الأنسب من الأشجار.

✔ تم تقدير عدد الأشجار المطلوب.

✔ تم حساب كمية الكربون السنوية.

✔ تم إنشاء مؤشرات تنفيذ المشروع تلقائياً.
""")
