import streamlit as st
import pandas as pd
import json
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

# ======================================================
# PAGE CONFIG
# ======================================================

st.set_page_config(
    page_title="ENVA",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ======================================================
# LOAD DATA
# ======================================================

DATA_PATH = Path("data")

try:
    with open(
        DATA_PATH / "ENVA_Final_Report.json",
        encoding="utf-8"
    ) as f:
        REPORT = json.load(f)

    SUMMARY = pd.read_csv(
        DATA_PATH / "ENVA_Final_Summary.csv"
    )

except Exception as e:
    st.error(
        f"❌ Error loading ENVA data files\n\n{e}"
    )
    st.stop()

# ======================================================
# CUSTOM STYLE
# ======================================================

st.markdown(
    """
    <style>

    .main {
        background-color: #f5f7fa;
    }

    h1, h2, h3 {
        color: #145A32;
    }

    div[data-testid="metric-container"] {
        background: white;
        padding: 15px;
        border-radius: 12px;
        border: 1px solid #dddddd;
        box-shadow: 0px 2px 8px rgba(0,0,0,0.08);
    }

    section[data-testid="stSidebar"] {
        background-color: #145A32;
    }

    </style>
    """,
    unsafe_allow_html=True
)

# ======================================================
# SIDEBAR
# ======================================================

st.sidebar.image(
    "https://img.icons8.com/fluency/96/earth-planet.png",
    width=90
)

st.sidebar.title("🌍 ENVA")

page = st.sidebar.radio(
    "Navigation",
    [
        "🏠 Home",
        "🛰️ Satellite Analysis",
        "🌍 Interactive Map",
        "📊 Dashboard",
        "🤖 AI Report",
        "🚨 Early Warning",
        "🚜 Agricultural Encroachments",
        "🌳 Smart Afforestation",
        "📥 Reports",
        "🔮 Future Expansion"
    ],
    key="main_navigation"
)

# ======================================================
# HOME PAGE
# ======================================================

if page == "🏠 Home":

    st.title("🌍 ENVA")

    st.subheader(
        "المنظومة الوطنية الذكية للرصد البيئي وتحليل صور الأقمار الصناعية ودعم اتخاذ القرار"
    )

    st.caption(
        "National Intelligent Platform for Environmental Monitoring, "
        "Satellite Image Analysis & Decision Support"
    )

    st.markdown("---")

    st.markdown(
        """
### 📖 About ENVA

ENVA is an intelligent environmental platform designed to support
decision makers using satellite imagery, artificial intelligence,
GIS technologies and environmental analytics.

---

### نبذة عن المشروع

يعتمد المشروع على تحليل صور الأقمار الصناعية باستخدام الذكاء الاصطناعي
لرصد التغيرات البيئية ودعم متخذي القرار من خلال لوحة معلومات ذكية.
"""
    )

    st.markdown("---")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric(
        "📍 Study Area",
        REPORT.get("study_area", "N/A")
    )

    c2.metric(
        "📅 Current Year",
        REPORT.get("current_year", "N/A")
    )

    c3.metric(
        "🎯 Accuracy",
        f'{REPORT.get("overall_accuracy", 96.4)} %'
    )

    c4.metric(
        "🛰️ Land Cover Classes",
        len(SUMMARY)
    )

# ======================================================
# SATELLITE ANALYSIS
# ======================================================

elif page == "🛰️ Satellite Analysis":

    st.title("🛰️ Satellite Analysis")

    st.subheader("تحليل صور الأقمار الصناعية")

    st.markdown(
        """
يعرض هذا القسم نتائج تحليل صور الأقمار الصناعية المستخدمة في مشروع ENVA.

This section presents the satellite image analysis results generated by ENVA.
"""
    )

    st.markdown("---")

    st.write("### Land Cover Statistics")

    st.dataframe(
        SUMMARY,
        use_container_width=True
    )

    st.markdown("---")

    st.write("### Environmental Indicators")

    col1, col2, col3 = st.columns(3)

    vegetation = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Vegetation",
            "Area_km2"
        ].sum()
    )

    urban = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Urban",
            "Area_km2"
        ].sum()
    )

    bare = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Bare Soil",
            "Area_km2"
        ].sum()
    )

    col1.metric(
        "🌳 Vegetation",
        f"{vegetation:.2f} km²"
    )

    col2.metric(
        "🏙️ Urban",
        f"{urban:.2f} km²"
    )

    col3.metric(
        "🟤 Bare Soil",
        f"{bare:.2f} km²"
    )

    st.markdown("---")

    st.success(
        """
### AI Summary

✅ Vegetation is the dominant land cover.

✅ Bare soil is decreasing.

✅ Urban expansion remains limited.

### ملخص الذكاء الاصطناعي

✅ الغطاء النباتي يمثل النسبة الأكبر.

✅ مساحة الأراضي الجرداء في انخفاض.

✅ التوسع العمراني ما زال ضمن الحدود الطبيعية.
"""
    )

# ======================================================
# INTERACTIVE MAP
# ======================================================

elif page == "🌍 Interactive Map":

    st.title("🌍 Interactive Environmental Map")

    st.subheader("الخريطة التفاعلية")

    st.markdown(
        """
تعرض هذه الصفحة خريطة الغطاء الأرضي الناتجة من تحليل صور الأقمار الصناعية.

This page displays the interactive land cover map generated from satellite imagery.
"""
    )

    st.markdown("---")

    html_file = DATA_PATH / "landcover_map_2026.html"

    if html_file.exists():

        try:

            from streamlit.components.v1 import html

            with open(
                html_file,
                "r",
                encoding="utf-8"
            ) as f:
                html_string = f.read()

            html(
                html_string,
                height=900,
                scrolling=True
            )

            st.success(
                "✅ Interactive map loaded successfully."
            )

        except Exception as e:

            st.error(
                f"❌ Error loading interactive map\n\n{e}"
            )

    else:

        st.error(
            "❌ Interactive map file not found."
        )

    st.markdown("---")

    st.info(
        """
### Available Layers

🛰️ Land Cover

🌳 Vegetation

🏙️ Urban Areas

🟤 Bare Soil

💧 Water Bodies

يمكن استخدام الخريطة للتكبير والتصغير واستعراض المناطق المختلفة.
"""
    )

# ======================================================
# ANALYTICS DASHBOARD
# ======================================================

elif page == "📊 Dashboard":

    st.title("📊 Environmental Analytics Dashboard")

    st.subheader("لوحة التحليلات البيئية")

    st.markdown(
        """
هذه الصفحة تعرض الإحصاءات البيئية المستخرجة من تحليل صور الأقمار الصناعية.

This dashboard summarizes the environmental indicators extracted from satellite imagery.
"""
    )

    st.markdown("---")

    # ===========================
    # KPI
    # ===========================

    c1, c2, c3, c4 = st.columns(4)

    total_area = float(
        SUMMARY["Area_km2"].sum()
    )

    vegetation = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Vegetation",
            "Area_km2"
        ].sum()
    )

    urban = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Urban",
            "Area_km2"
        ].sum()
    )

    bare = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Bare Soil",
            "Area_km2"
        ].sum()
    )

    c1.metric(
        "📍 Study Area",
        REPORT.get("study_area", "N/A")
    )

    c2.metric(
        "🛰️ Classes",
        len(SUMMARY)
    )

    c3.metric(
        "🌳 Vegetation",
        f"{vegetation:.2f} km²"
    )

    c4.metric(
        "📐 Total Area",
        f"{total_area:.2f} km²"
    )

    st.markdown("---")

    # ===========================
    # LAND COVER TABLE
    # ===========================

    st.subheader("Land Cover Statistics")

    st.dataframe(
        SUMMARY,
        use_container_width=True
    )

    st.markdown("---")

    # ===========================
    # SIMPLE BAR CHART
    # ===========================

    st.subheader("Land Cover Distribution")

    chart_data = (
        SUMMARY
        .set_index("Class_Name")["Area_km2"]
    )

    st.bar_chart(chart_data)

    st.markdown("---")

    # ===========================
    # AI INSIGHTS
    # ===========================

    st.subheader("🤖 AI Insights")

    if vegetation > bare:

        st.success(
            """
Vegetation is the dominant land cover.

الغطاء النباتي يمثل المساحة الأكبر داخل منطقة الدراسة.
"""
        )

    if bare > urban:

        st.info(
            """
Bare soil is larger than urban expansion.

الأراضي الجرداء ما زالت أكبر من التوسع العمراني.
"""
        )

    if urban < vegetation:

        st.success(
            """
Urban expansion is still limited.

التوسع العمراني ما زال محدودًا مقارنة بالغطاء النباتي.
"""
        )

# ======================================================
# AI ENVIRONMENTAL REPORT
# ======================================================

elif page == "🤖 AI Report":

    st.title("🤖 ENVA AI Environmental Assistant")

    st.subheader("المساعد الذكي لتحليل البيئة")

    st.markdown(
        """
يقوم الذكاء الاصطناعي بتحليل نتائج صور الأقمار الصناعية
واستخراج أهم المؤشرات البيئية بصورة تلقائية.

The AI engine automatically interprets satellite analysis
and generates environmental insights.
"""
    )

    st.markdown("---")

    # =====================================
    # Load Statistics
    # =====================================

    vegetation = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Vegetation",
            "Area_km2"
        ].sum()
    )

    urban = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Urban",
            "Area_km2"
        ].sum()
    )

    bare = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Bare Soil",
            "Area_km2"
        ].sum()
    )

    total = float(
        SUMMARY["Area_km2"].sum()
    )

    # =====================================
    # Prevent ZeroDivisionError
    # =====================================

    if total > 0:

        vegetation_percent = vegetation / total * 100
        urban_percent = urban / total * 100
        bare_percent = bare / total * 100

    else:

        vegetation_percent = 0.0
        urban_percent = 0.0
        bare_percent = 0.0

    # =====================================
    # Executive Summary
    # =====================================

    st.markdown("## 📄 Executive Summary")

    st.success(
        f"""
### 🇬🇧 English

The AI environmental analysis indicates that vegetation is the dominant land cover.

🌳 Vegetation: **{vegetation_percent:.1f}%**

🏙️ Urban: **{urban_percent:.1f}%**

🟤 Bare Soil: **{bare_percent:.1f}%**

Overall environmental conditions appear stable based on the current satellite observations.

---

### 🇪🇬 العربية

يشير تحليل الذكاء الاصطناعي إلى أن الغطاء النباتي هو العنصر المسيطر داخل منطقة الدراسة.

🌳 الغطاء النباتي: **{vegetation_percent:.1f}%**

🏙️ العمران: **{urban_percent:.1f}%**

🟤 الأراضي الجرداء: **{bare_percent:.1f}%**

تشير النتائج الحالية إلى أن الوضع البيئي مستقر اعتمادًا على بيانات الأقمار الصناعية.
"""
    )

    st.markdown("---")

    # =====================================
    # AI Status Cards
    # =====================================

    if vegetation_percent >= 60:
        status = "🟢 Stable"
    elif vegetation_percent >= 40:
        status = "🟡 Moderate"
    else:
        status = "🔴 Critical"

    if bare_percent >= 20:
        risk = "🔴 High"
    elif bare_percent >= 10:
        risk = "🟡 Medium"
    else:
        risk = "🟢 Low"

    confidence = REPORT.get(
        "overall_accuracy",
        96.4
    )

    col1, col2, col3 = st.columns(3)

    col1.metric(
        "Environmental Status",
        status
    )

    col2.metric(
        "Risk Level",
        risk
    )

    col3.metric(
        "AI Confidence",
        f"{confidence}%"
    )

    st.markdown("---")
    # =====================================
    # AI ENVIRONMENTAL ASSESSMENT
    # =====================================

    st.subheader("🧠 AI Environmental Assessment")

    if vegetation_percent >= 70:

        ai_text = """
### 🌿 Environmental Interpretation

The study area is environmentally healthy.

Vegetation is the dominant land cover,
indicating a stable ecosystem with relatively low environmental pressure.

Urban expansion remains limited.

Current satellite observations suggest that
the environmental condition is suitable for sustainable development.

---

### 🇪🇬 التفسير البيئي

تشير نتائج الذكاء الاصطناعي إلى أن المنطقة تتمتع بحالة بيئية جيدة.

يسيطر الغطاء النباتي على معظم مساحة المنطقة،
مما يعكس استقرارًا بيئيًا وانخفاض الضغوط البشرية.

ولا يزال التوسع العمراني محدودًا،
وهو ما يساعد على الحفاظ على الموارد الطبيعية.
"""

    elif vegetation_percent >= 50:

        ai_text = """
### 🌿 Environmental Interpretation

The environmental condition is acceptable.

Vegetation is still dominant,
however continuous monitoring is recommended
to detect any future land cover changes.

Urban development should be monitored periodically.

---

### 🇪🇬 التفسير البيئي

تشير النتائج إلى أن الوضع البيئي جيد بصورة عامة.

ورغم سيطرة الغطاء النباتي،
فإن المتابعة الدورية ضرورية
لاكتشاف أي تغيرات مستقبلية.

كما يوصى بمراقبة التوسع العمراني باستمرار.
"""

    else:

        ai_text = """
### ⚠ Environmental Interpretation

The AI engine detected a decline in vegetation.

This may indicate environmental degradation,
urban expansion,
or increasing land degradation.

Immediate monitoring is recommended.

---

### 🇪🇬 التفسير البيئي

اكتشف الذكاء الاصطناعي انخفاضًا واضحًا في الغطاء النباتي.

وقد يشير ذلك إلى
التوسع العمراني،
أو تدهور الأراضي،
أو انخفاض جودة البيئة.

يوصى بإجراء متابعة عاجلة.
"""

    st.success(ai_text)

    st.markdown("---")

    # =====================================
    # AI SMART RECOMMENDATIONS
    # =====================================

    st.subheader("🎯 AI Smart Recommendations")

    recommendations = []

    # Vegetation

    if vegetation_percent >= 70:

        recommendations.append(
            "🌳 Preserve existing vegetation and protect agricultural land."
        )

    elif vegetation_percent >= 50:

        recommendations.append(
            "🌱 Increase vegetation monitoring every season."
        )

    else:

        recommendations.append(
            "🚨 Immediate vegetation restoration is recommended."
        )

    # Bare Soil

    if bare_percent >= 20:

        recommendations.append(
            "🌾 Launch large-scale afforestation projects in bare soil regions."
        )

    elif bare_percent >= 10:

        recommendations.append(
            "🌱 Prioritize tree planting in degraded land."
        )

    # Urban

    if urban_percent >= 15:

        recommendations.append(
            "🏙️ Monitor urban expansion using monthly satellite imagery."
        )

    else:

        recommendations.append(
            "🏡 Urban growth is currently under acceptable limits."
        )

    # Water and Monitoring

    recommendations.append(
        "💧 Continue monitoring water resources using Sentinel imagery."
    )

    recommendations.append(
        "🛰️ Update environmental monitoring every month."
    )

    recommendations.append(
        "🤖 AI recommends maintaining continuous satellite observation."
    )

    for item in recommendations:

        st.write(item)

    st.markdown("---")

    # ==========================================================
    # AI DECISION SUPPORT
    # ==========================================================

    st.subheader("🧠 AI Decision Support")

    # =====================================
    # Sustainability Score
    # =====================================

    sustainability_score = round(
        vegetation_percent
        - (bare_percent * 0.5)
        - (urban_percent * 0.3),
        1
    )

    sustainability_score = max(
        0,
        min(100, sustainability_score)
    )

    # =====================================
    # Environmental Risk Score
    # =====================================

    risk_score = round(
        (bare_percent * 1.5)
        + urban_percent,
        1
    )

    # =====================================
    # Risk Level
    # =====================================

    if risk_score < 20:

        risk_level = "🟢 LOW"

    elif risk_score < 40:

        risk_level = "🟡 MODERATE"

    else:

        risk_level = "🔴 HIGH"

    # =====================================
    # Final AI Decision
    # =====================================

    if sustainability_score >= 70:

        decision = """
### ✅ AI Final Decision

The study area is environmentally stable.

No urgent intervention is required.

Routine environmental monitoring is recommended.

---

### 🇪🇬 القرار النهائي

المنطقة مستقرة بيئيًا.

لا توجد حاجة إلى تدخل عاجل.

يوصى بالمتابعة الدورية فقط.
"""

    elif sustainability_score >= 50:

        decision = """
### ⚠ AI Final Decision

The study area is environmentally acceptable.

Preventive environmental actions are recommended.

---

### 🇪🇬 القرار النهائي

الوضع البيئي جيد بصورة عامة.

يوصى باتخاذ إجراءات وقائية للحفاظ على الموارد الطبيعية.
"""

    else:

        decision = """
### 🚨 AI Final Decision

Environmental intervention is recommended.

Restoration and afforestation programs should be considered.

---

### 🇪🇬 القرار النهائي

يوصى بتدخل بيئي عاجل.

ينصح بتنفيذ برامج إعادة التأهيل والتشجير.
"""

    # =====================================
    # Metrics
    # =====================================

    col1, col2 = st.columns(2)

    col1.metric(
        "🌍 Sustainability Score",
        f"{sustainability_score}/100"
    )

    col2.metric(
        "⚠ Environmental Risk",
        risk_level
    )

    st.markdown("---")

    st.success(decision)

    st.markdown("---")

    st.info(
        """
### Decision Support

ENVA AI automatically summarizes environmental indicators
to support environmental planning and decision making.

يقوم الذكاء الاصطناعي بتحويل نتائج تحليل صور الأقمار الصناعية
إلى تقرير واضح يساعد متخذي القرار.
"""
    )

    st.caption(
        "Generated automatically by ENVA AI Decision Support Engine."
    )

# ======================================================
# SMART AFFORESTATION
# ======================================================

elif page == "🌳 Smart Afforestation":

    st.title("🌳 Smart Afforestation")

    st.subheader("التشجير الذكي")

    st.markdown(
        """
تستخدم هذه الصفحة نتائج الذكاء الاصطناعي وصور الأقمار الصناعية
لتحديد المناطق المناسبة للتشجير وتحسين الغطاء النباتي
ودعم التنمية البيئية المستدامة.

This module uses AI-based satellite analysis
to identify suitable afforestation areas
and support sustainable environmental planning.
"""
    )

    st.markdown("---")

    # ======================================================
    # LOAD DATA
    # ======================================================

    try:

        with open(
            DATA_PATH / "ENVA_Afforestation_Report.json",
            encoding="utf-8"
        ) as f:

            AFF_REPORT = json.load(f)

        AFF_SUMMARY = pd.read_csv(
            DATA_PATH / "ENVA_Afforestation_Summary.csv"
        )

    except Exception as e:

        st.error(
            f"❌ Error loading Smart Afforestation files\n\n{e}"
        )

        st.stop()

    st.success(
        "✅ Smart Afforestation data loaded successfully."
    )

    st.markdown("---")

    # ======================================================
    # AI SUMMARY
    # ======================================================

    st.subheader("🤖 AI Summary")

    ai_summary = AFF_REPORT.get("AI_Summary")

    if ai_summary:

        st.json(ai_summary)

    else:

        st.info(
            "AI summary is not available."
        )

    st.markdown("---")

    # ======================================================
    # SUMMARY TABLE
    # ======================================================

    st.subheader("📋 Afforestation Summary")

    st.dataframe(
        AFF_SUMMARY,
        use_container_width=True
    )

    st.markdown("---")

    # ======================================================
    # MAIN INDICATORS
    # ======================================================

    st.subheader("📊 Key Indicators")

    if "Recommended Area (km²)" in AFF_SUMMARY.columns:

        area = float(
            AFF_SUMMARY["Recommended Area (km²)"].iloc[0]
        )

    else:

        area = 0.0

    if "Estimated Trees" in AFF_SUMMARY.columns:

        trees = int(
            AFF_SUMMARY["Estimated Trees"].iloc[0]
        )

    else:

        trees = 0

    if "Annual Carbon (ton CO₂)" in AFF_SUMMARY.columns:

        carbon = float(
            AFF_SUMMARY["Annual Carbon (ton CO₂)"].iloc[0]
        )

    else:

        carbon = 0.0

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "🌱 Target Area",
        f"{area:.2f} km²"
    )

    c2.metric(
        "🌳 Estimated Trees",
        f"{trees:,}"
    )

    c3.metric(
        "🌍 Annual CO₂",
        f"{carbon:,.1f} ton"
    )

    st.markdown("---")

    # ======================================================
    # DECISION SUPPORT
    # ======================================================

    st.subheader("🧠 Smart Afforestation Decision Support")

    st.info(
        """
ENVA AI analyzes satellite imagery to recommend
the most suitable afforestation strategy.

The generated recommendations improve vegetation,
increase carbon sequestration,
and support sustainable environmental management.

---

يقوم نظام ENVA بتحليل صور الأقمار الصناعية
لتحديد أفضل مواقع التشجير.

وتساعد النتائج في زيادة الغطاء النباتي،
ورفع معدل امتصاص الكربون،
ودعم التنمية البيئية المستدامة.
"""
    )

    st.markdown("---")

    # ======================================================
    # RECOMMENDED ACTIONS
    # ======================================================

    st.subheader("🎯 Recommended Actions")

    actions = []

    if area > 0:

        actions.append(
            f"🌱 Afforest approximately {area:.2f} km²."
        )

    if trees > 0:

        actions.append(
            f"🌳 Plant approximately {trees:,} trees."
        )

    if "Recommended Tree" in AFF_SUMMARY.columns:

        recommended_tree = str(
            AFF_SUMMARY["Recommended Tree"].iloc[0]
        )

        actions.append(
            f"🌲 Recommended species: {recommended_tree}"
        )

    actions.append(
        "🛰️ Continue monitoring using Sentinel satellite imagery."
    )

    actions.append(
        "🌍 Update the environmental assessment periodically."
    )

    for item in actions:

        st.write(item)

    st.markdown("---")

    # ======================================================
    # AFFORESTATION SUMMARY TABLE
    # ======================================================

    st.subheader("🌱 Afforestation Analysis Summary")

    st.dataframe(
        AFF_SUMMARY,
        use_container_width=True
    )

    st.markdown("---")

    # ======================================================
    # BASIC INDICATORS
    # ======================================================

    st.subheader("📊 Afforestation Indicators")

    col1, col2, col3 = st.columns(3)

    records = len(AFF_SUMMARY)

    if "Recommended Area (km²)" in AFF_SUMMARY.columns:

        recommended_area = float(
            AFF_SUMMARY["Recommended Area (km²)"].sum()
        )

    else:

        recommended_area = 0.0

    if "Estimated Trees" in AFF_SUMMARY.columns:

        estimated_trees = int(
            AFF_SUMMARY["Estimated Trees"].sum()
        )

    else:

        estimated_trees = 0

    col1.metric(
        "📄 Analysis Records",
        records
    )

    col2.metric(
        "🌳 Recommended Area",
        f"{recommended_area:.2f} km²"
    )

    col3.metric(
        "🌱 Estimated Trees",
        f"{estimated_trees:,}"
    )

    st.markdown("---")

    # ======================================================
    # AI DECISION SUPPORT
    # ======================================================

    st.subheader("🤖 AI Decision Support")

    st.info(
        """
ENVA AI analyzes satellite imagery to determine the best locations
for afforestation according to environmental suitability.

يقوم الذكاء الاصطناعي بتحليل صور الأقمار الصناعية
لتحديد أفضل المناطق المناسبة للتشجير.
"""
    )

    st.markdown("---")

    # ======================================================
    # RECOMMENDED ACTIONS
    # ======================================================

    st.subheader("🎯 Recommended Actions")

    actions = []

    if "Recommended Tree" in AFF_SUMMARY.columns:

        tree = str(
            AFF_SUMMARY["Recommended Tree"].iloc[0]
        )

        actions.append(
            f"🌳 Recommended tree species: {tree}"
        )

    if "Recommended Area (km²)" in AFF_SUMMARY.columns:

        area = float(
            AFF_SUMMARY["Recommended Area (km²)"].iloc[0]
        )

        actions.append(
            f"🌱 Afforest approximately {area:.2f} km²."
        )

    if "Estimated Trees" in AFF_SUMMARY.columns:

        trees = int(
            AFF_SUMMARY["Estimated Trees"].iloc[0]
        )

        actions.append(
            f"🌲 Plant approximately {trees:,} trees."
        )

    if "Annual Carbon (ton CO₂)" in AFF_SUMMARY.columns:

        carbon = float(
            AFF_SUMMARY["Annual Carbon (ton CO₂)"].iloc[0]
        )

        actions.append(
            f"🌍 Expected annual CO₂ sequestration: "
            f"{carbon:,.1f} tons."
        )

    for action in actions:

        st.write(action)

    st.markdown("---")

    # ======================================================
    # AI RECOMMENDATION
    # ======================================================

    st.success(
        """
### ✅ AI Recommendation

The proposed afforestation program is environmentally suitable
and is expected to improve vegetation cover,
increase carbon sequestration,
and support sustainable land management.

---

### التوصية النهائية

يوصي نظام ENVA بالبدء في تنفيذ برنامج التشجير
لتحسين الغطاء النباتي وزيادة الاستدامة البيئية.
"""
    )

    st.markdown("---")

    # ======================================================
    # CARBON SEQUESTRATION
    # ======================================================

    st.subheader("🌍 Estimated Carbon Sequestration")

    carbon_report = AFF_REPORT.get(
        "Carbon_Report",
        {}
    )

    if "Estimated Trees" in carbon_report:

        carbon_trees = carbon_report.get(
            "Estimated Trees"
        )

    else:

        carbon_trees = trees

    if "Estimated Annual Carbon (ton CO₂)" in carbon_report:

        annual_carbon = carbon_report.get(
            "Estimated Annual Carbon (ton CO₂)"
        )

    else:

        annual_carbon = carbon

    c1, c2 = st.columns(2)

    c1.metric(
        "🌱 Estimated Trees",
        f"{int(carbon_trees):,}"
    )

    c2.metric(
        "🌍 Annual CO₂",
        f"{float(annual_carbon):,.1f} ton"
    )

    st.markdown("---")

    # ======================================================
    # PROJECT IMPACT
    # ======================================================

    st.subheader("📈 Project Impact")

    if "Estimated Cost (EGP)" in AFF_SUMMARY.columns:

        cost = AFF_SUMMARY[
            "Estimated Cost (EGP)"
        ].iloc[0]

    else:

        cost = "N/A"

    if "Recommended Tree" in AFF_SUMMARY.columns:

        recommended_tree = str(
            AFF_SUMMARY["Recommended Tree"].iloc[0]
        )

    else:

        recommended_tree = "N/A"

    col1, col2 = st.columns(2)

    if isinstance(cost, (int, float)):

        col1.metric(
            "💰 Estimated Cost",
            f"{cost:,.0f} EGP"
        )

    else:

        col1.metric(
            "💰 Estimated Cost",
            cost
        )

    col2.metric(
        "🌳 Recommended Tree",
        recommended_tree
    )

    st.markdown("---")

    # ======================================================
    # PROJECT STATUS
    # ======================================================

    st.subheader("🚀 ENVA Decision Support")

    left, right = st.columns([2, 1])

    with left:

        st.markdown(
            """
### 🌍 ENVA Recommendation

Based on satellite imagery and AI analysis,
the proposed afforestation project is expected to:

- 🌳 Increase vegetation cover
- 🌍 Enhance carbon sequestration
- 💧 Protect soil resources
- 🌦 Improve climate resilience
- 🌱 Support sustainable environmental development

---

### توصية ENVA

يوصي النظام بتنفيذ برنامج التشجير المقترح
لتحسين الغطاء النباتي وخفض الانبعاثات
ودعم التنمية البيئية المستدامة.
"""
        )

    with right:

        st.metric(
            "Project Status",
            "READY"
        )

        st.metric(
            "AI Decision",
            "APPROVED"
        )

        st.metric(
            "Recommended Tree",
            str(recommended_tree)
        )

    st.markdown("---")

    # ======================================================
    # DOWNLOAD RESULTS
    # ======================================================

    st.subheader("📥 Download Results")

    col1, col2 = st.columns(2)

    with col1:

        csv = AFF_SUMMARY.to_csv(
            index=False
        ).encode("utf-8")

        st.download_button(
            label="⬇ Download Summary CSV",
            data=csv,
            file_name="ENVA_Afforestation_Summary.csv",
            mime="text/csv",
            key="download_afforestation_csv"
        )

    with col2:

        report = json.dumps(
            AFF_REPORT,
            indent=4,
            ensure_ascii=False
        )

        st.download_button(
            label="⬇ Download AI Report",
            data=report,
            file_name="ENVA_Afforestation_Report.json",
            mime="application/json",
            key="download_afforestation_report"
        )

    st.markdown("---")

    st.success(
        """
### ✅ Smart Afforestation Module Completed Successfully

The AI analysis has generated afforestation recommendations,
estimated environmental benefits,
and project implementation indicators.

تم إنشاء جميع مؤشرات مشروع التشجير الذكي بنجاح،
وأصبحت النتائج جاهزة للتنزيل والاستخدام.
"""
    )

    st.caption(
        "Generated automatically by ENVA AI Smart Afforestation Engine."
    )

# ============================================================
# END OF PART 2
# ============================================================
# ==========================================================
# AI ENVIRONMENTAL REPORT
# ==========================================================

elif page == "🤖 AI Report":

    st.title("🤖 ENVA AI Environmental Assistant")

    st.subheader("المساعد الذكي لتحليل البيئة")

    st.markdown("""
يقوم الذكاء الاصطناعي بتحليل نتائج صور الأقمار الصناعية
واستخراج أهم المؤشرات البيئية بصورة تلقائية.

The AI engine automatically interprets satellite analysis
and generates environmental insights.
""")

    st.markdown("---")

    # =====================================
    # Load Statistics
    # =====================================

    vegetation = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Vegetation",
            "Area_km2"
        ].sum()
    )

    urban = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Urban",
            "Area_km2"
        ].sum()
    )

    bare = float(
        SUMMARY.loc[
            SUMMARY["Class_Name"] == "Bare Soil",
            "Area_km2"
        ].sum()
    )

    total = float(
        SUMMARY["Area_km2"].sum()
    )

    # =====================================
    # Prevent ZeroDivisionError
    # =====================================

    if total > 0:
        vegetation_percent = vegetation / total * 100
        urban_percent = urban / total * 100
        bare_percent = bare / total * 100
    else:
        vegetation_percent = 0.0
        urban_percent = 0.0
        bare_percent = 0.0

    # =====================================
    # Executive Summary
    # =====================================

    st.markdown("## 📄 Executive Summary")

    st.success(
        f"""
### 🇬🇧 English

The AI environmental analysis indicates that vegetation is the dominant land cover.

🌳 Vegetation: **{vegetation_percent:.1f}%**

🏙️ Urban: **{urban_percent:.1f}%**

🟤 Bare Soil: **{bare_percent:.1f}%**

Overall environmental conditions appear stable based on the current satellite observations.

---

### 🇪🇬 العربية

يشير تحليل الذكاء الاصطناعي إلى أن الغطاء النباتي هو العنصر المسيطر داخل منطقة الدراسة.

🌳 الغطاء النباتي: **{vegetation_percent:.1f}%**

🏙️ العمران: **{urban_percent:.1f}%**

🟤 الأراضي الجرداء: **{bare_percent:.1f}%**

تشير النتائج الحالية إلى أن الوضع البيئي مستقر اعتمادًا على بيانات الأقمار الصناعية.
"""
    )

    st.markdown("---")

    # =====================================
    # AI Status Cards
    # =====================================

    if vegetation_percent >= 60:
        status = "🟢 Stable"
    elif vegetation_percent >= 40:
        status = "🟡 Moderate"
    else:
        status = "🔴 Critical"

    if bare_percent >= 20:
        risk = "🔴 High"
    elif bare_percent >= 10:
        risk = "🟡 Medium"
    else:
        risk = "🟢 Low"

    confidence = REPORT.get("overall_accuracy", 96.4)

    col1, col2, col3 = st.columns(3)

    col1.metric(
        "Environmental Status",
        status
    )

    col2.metric(
        "Risk Level",
        risk
    )

    col3.metric(
        "AI Confidence",
        f"{confidence}%"
    )

    st.markdown("---")

    # =====================================
    # AI ENVIRONMENTAL ASSESSMENT
    # =====================================

    st.subheader("🧠 AI Environmental Assessment")

    if vegetation_percent >= 70:

        ai_text = """
### 🌿 Environmental Interpretation

The study area is environmentally healthy.

Vegetation is the dominant land cover,
indicating a stable ecosystem with relatively low environmental pressure.

Urban expansion remains limited.

Current satellite observations suggest that
the environmental condition is suitable for sustainable development.

---

### 🇪🇬 التفسير البيئي

تشير نتائج الذكاء الاصطناعي إلى أن المنطقة تتمتع بحالة بيئية جيدة.

يسيطر الغطاء النباتي على معظم مساحة المنطقة،
مما يعكس استقرارًا بيئيًا وانخفاض الضغوط البشرية.

ولا يزال التوسع العمراني محدودًا،
وهو ما يساعد على الحفاظ على الموارد الطبيعية.
"""

    elif vegetation_percent >= 50:

        ai_text = """
### 🌿 Environmental Interpretation

The environmental condition is acceptable.

Vegetation is still dominant,
however continuous monitoring is recommended
to detect any future land cover changes.

Urban development should be monitored periodically.

---

### 🇪🇬 التفسير البيئي

تشير النتائج إلى أن الوضع البيئي جيد بصورة عامة.

ورغم سيطرة الغطاء النباتي،
فإن المتابعة الدورية ضرورية
لاكتشاف أي تغيرات مستقبلية.

كما يوصى بمراقبة التوسع العمراني باستمرار.
"""

    else:

        ai_text = """
### ⚠ Environmental Interpretation

The AI engine detected a decline in vegetation.

This may indicate environmental degradation,
urban expansion,
or increasing land degradation.

Immediate monitoring is recommended.

---

### 🇪🇬 التفسير البيئي

اكتشف الذكاء الاصطناعي انخفاضًا واضحًا في الغطاء النباتي.

وقد يشير ذلك إلى
التوسع العمراني،
أو تدهور الأراضي،
أو انخفاض جودة البيئة.

يوصى بإجراء متابعة عاجلة.
"""

    st.success(ai_text)

    st.markdown("---")

    # =====================================
    # AI SMART RECOMMENDATIONS
    # =====================================

    st.subheader("🎯 AI Smart Recommendations")

    recommendations = []

    if vegetation_percent >= 70:

        recommendations.append(
            "🌳 Preserve existing vegetation and protect agricultural land."
        )

    elif vegetation_percent >= 50:

        recommendations.append(
            "🌱 Increase vegetation monitoring every season."
        )

    else:

        recommendations.append(
            "🚨 Immediate vegetation restoration is recommended."
        )

    if bare_percent >= 20:

        recommendations.append(
            "🌾 Launch large-scale afforestation projects in bare soil regions."
        )

    elif bare_percent >= 10:

        recommendations.append(
            "🌱 Prioritize tree planting in degraded land."
        )

    if urban_percent >= 15:

        recommendations.append(
            "🏙️ Monitor urban expansion using monthly satellite imagery."
        )

    else:

        recommendations.append(
            "🏡 Urban growth is currently under acceptable limits."
        )

    recommendations.append(
        "💧 Continue monitoring water resources using Sentinel imagery."
    )

    recommendations.append(
        "🛰️ Update environmental monitoring every month."
    )

    recommendations.append(
        "🤖 AI recommends maintaining continuous satellite observation."
    )

    for item in recommendations:
        st.write(item)

    st.markdown("---")

    # ==========================================================
    # AI DECISION SUPPORT
    # ==========================================================

    st.subheader("🧠 AI Decision Support")

    # =====================================
    # Sustainability Score
    # =====================================

    sustainability_score = round(
        vegetation_percent
        - (bare_percent * 0.5)
        - (urban_percent * 0.3),
        1
    )

    sustainability_score = max(
        0,
        min(100, sustainability_score)
    )

    # =====================================
    # Environmental Risk Score
    # =====================================

    risk_score = round(
        (bare_percent * 1.5)
        + urban_percent,
        1
    )

    # =====================================
    # Risk Level
    # =====================================

    if risk_score < 20:
        risk_level = "🟢 LOW"

    elif risk_score < 40:
        risk_level = "🟡 MODERATE"

    else:
        risk_level = "🔴 HIGH"

    # =====================================
    # Final AI Decision
    # =====================================

    if sustainability_score >= 70:

        decision = """
### ✅ AI Final Decision

The study area is environmentally stable.

No urgent intervention is required.

Routine environmental monitoring is recommended.

---

### 🇪🇬 القرار النهائي

المنطقة مستقرة بيئيًا.

لا توجد حاجة إلى تدخل عاجل.

يوصى بالمتابعة الدورية فقط.
"""

    elif sustainability_score >= 50:

        decision = """
### ⚠ AI Final Decision

The study area is environmentally acceptable.

Preventive environmental actions are recommended.

---

### 🇪🇬 القرار النهائي

الوضع البيئي جيد بصورة عامة.

يوصى باتخاذ إجراءات وقائية للحفاظ على الموارد الطبيعية.
"""

    else:

        decision = """
### 🚨 AI Final Decision

Environmental intervention is recommended.

Restoration and afforestation programs should be considered.

---

### 🇪🇬 القرار النهائي

يوصى بتدخل بيئي عاجل.

ينصح بتنفيذ برامج إعادة التأهيل والتشجير.
"""

    # =====================================
    # Metrics
    # =====================================

    col1, col2 = st.columns(2)

    col1.metric(
        "🌍 Sustainability Score",
        f"{sustainability_score}/100"
    )

    col2.metric(
        "⚠ Environmental Risk",
        risk_level
    )

    st.markdown("---")

    st.success(decision)

    st.markdown("---")

    st.info(
        """
### Decision Support

ENVA AI automatically summarizes environmental indicators
to support environmental planning and decision making.

يقوم الذكاء الاصطناعي بتحويل نتائج تحليل صور الأقمار الصناعية
إلى تقرير واضح يساعد متخذي القرار.
"""
    )

    st.caption(
        "Generated automatically by ENVA AI Decision Support Engine."
    )


# ======================================================
# SMART AFFORESTATION
# ======================================================

elif page == "🌳 Smart Afforestation":

    st.title("🌳 Smart Afforestation")

    st.subheader("التشجير الذكي")

    st.markdown("""
تستخدم هذه الصفحة نتائج الذكاء الاصطناعي وصور الأقمار الصناعية
لتحديد المناطق المناسبة للتشجير وتحسين الغطاء النباتي
ودعم التنمية البيئية المستدامة.

This module uses AI-based satellite analysis
to identify suitable afforestation areas
and support sustainable environmental planning.
""")

    st.markdown("---")

    # ======================================================
    # LOAD DATA
    # ======================================================

    try:

        with open(
            DATA_PATH / "ENVA_Afforestation_Report.json",
            encoding="utf-8"
        ) as f:

            AFF_REPORT = json.load(f)

        AFF_SUMMARY = pd.read_csv(
            DATA_PATH / "ENVA_Afforestation_Summary.csv"
        )

    except Exception as e:

        st.error(
            f"❌ Error loading Smart Afforestation files\n\n{e}"
        )

        st.stop()

    st.success(
        "✅ Smart Afforestation data loaded successfully."
    )

    st.markdown("---")

    # ======================================================
    # AI SUMMARY
    # ======================================================

    st.subheader("🤖 AI Summary")

    ai_summary = AFF_REPORT.get("AI_Summary")

    if ai_summary:
        st.json(ai_summary)
    else:
        st.info(
            "AI summary is not available."
        )

    st.markdown("---")

    # ======================================================
    # SUMMARY TABLE
    # ======================================================

    st.subheader("📋 Afforestation Summary")

    st.dataframe(
        AFF_SUMMARY,
        use_container_width=True
    )

    st.markdown("---")

    # ======================================================
    # MAIN INDICATORS
    # ======================================================

    st.subheader("📊 Key Indicators")

    area = float(
        AFF_SUMMARY.get(
            "Recommended Area (km²)",
            pd.Series([0])
        ).iloc[0]
    )

    trees = int(
        AFF_SUMMARY.get(
            "Estimated Trees",
            pd.Series([0])
        ).iloc[0]
    )

    carbon = float(
        AFF_SUMMARY.get(
            "Annual Carbon (ton CO₂)",
            pd.Series([0])
        ).iloc[0]
    )

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "🌱 Target Area",
        f"{area:.2f} km²"
    )

    c2.metric(
        "🌳 Estimated Trees",
        f"{trees:,}"
    )

    c3.metric(
        "🌍 Annual CO₂",
        f"{carbon:,.1f} ton"
    )

    st.markdown("---")

    # ======================================================
    # DECISION SUPPORT
    # ======================================================

    st.subheader("🧠 Smart Afforestation Decision Support")

    st.info(
        """
ENVA AI analyzes satellite imagery to recommend
the most suitable afforestation strategy.

The generated recommendations improve vegetation,
increase carbon sequestration,
and support sustainable environmental management.

---

يقوم نظام ENVA بتحليل صور الأقمار الصناعية
لتحديد أفضل مواقع التشجير.

وتساعد النتائج في زيادة الغطاء النباتي،
ورفع معدل امتصاص الكربون،
ودعم التنمية البيئية المستدامة.
"""
    )

    st.markdown("---")

    # ======================================================
    # RECOMMENDED ACTIONS
    # ======================================================

    st.subheader("🎯 Recommended Actions")

    actions = []

    if area > 0:

        actions.append(
            f"🌱 Afforest approximately {area:.2f} km²."
        )

    if trees > 0:

        actions.append(
            f"🌳 Plant approximately {trees:,} trees."
        )

    if "Recommended Tree" in AFF_SUMMARY.columns:

        actions.append(
            f"🌲 Recommended species: {AFF_SUMMARY['Recommended Tree'].iloc[0]}"
        )

    actions.append(
        "🛰️ Continue monitoring using Sentinel satellite imagery."
    )

    actions.append(
        "🌍 Update the environmental assessment periodically."
    )

    for item in actions:
        st.write(item)

    st.markdown("---")

    # ======================================================
    # AI RECOMMENDATION
    # ======================================================

    st.subheader("🤖 AI Recommendation")

    st.success(
        """
### ✅ AI Recommendation

The proposed afforestation program is environmentally suitable
and is expected to improve vegetation cover,
increase carbon sequestration,
and support sustainable land management.

---

### التوصية النهائية

يوصي نظام ENVA بالبدء في تنفيذ برنامج التشجير
لتحسين الغطاء النباتي وزيادة الاستدامة البيئية.
"""
    )

    st.markdown("---")

    # ======================================================
    # CARBON SEQUESTRATION
    # ======================================================

    st.subheader("🌍 Estimated Carbon Sequestration")

    carbon_report = AFF_REPORT.get(
        "Carbon_Report",
        {}
    )

    if "Estimated Trees" in carbon_report:
        carbon_trees = carbon_report.get("Estimated Trees")
    elif "Estimated Trees" in AFF_SUMMARY.columns:
        carbon_trees = AFF_SUMMARY["Estimated Trees"].iloc[0]
    else:
        carbon_trees = 0

    if "Estimated Annual Carbon (ton CO₂)" in carbon_report:
        annual_carbon = carbon_report.get(
            "Estimated Annual Carbon (ton CO₂)"
        )
    elif "Annual Carbon (ton CO₂)" in AFF_SUMMARY.columns:
        annual_carbon = AFF_SUMMARY[
            "Annual Carbon (ton CO₂)"
        ].iloc[0]
    else:
        annual_carbon = 0

    c1, c2 = st.columns(2)

    c1.metric(
        "🌱 Estimated Trees",
        f"{int(carbon_trees):,}"
    )

    c2.metric(
        "🌍 Annual CO₂",
        f"{float(annual_carbon):,.1f} ton"
    )

    st.markdown("---")

    # ======================================================
    # PROJECT IMPACT
    # ======================================================

    st.subheader("📈 Project Impact")

    cost = (
        AFF_SUMMARY["Estimated Cost (EGP)"].iloc[0]
        if "Estimated Cost (EGP)" in AFF_SUMMARY.columns
        else "N/A"
    )

    recommended_tree = (
        AFF_SUMMARY["Recommended Tree"].iloc[0]
        if "Recommended Tree" in AFF_SUMMARY.columns
        else "N/A"
    )

    col1, col2 = st.columns(2)

    col1.metric(
        "💰 Estimated Cost",
        f"{cost:,} EGP"
        if isinstance(cost, (int, float))
        else cost
    )

    col2.metric(
        "🌳 Recommended Tree",
        recommended_tree
    )

    st.markdown("---")

    # ======================================================
    # PROJECT STATUS
    # ======================================================

    st.subheader("🚀 ENVA Decision Support")

    left, right = st.columns([2, 1])

    with left:

        st.markdown(
            """
### 🌍 ENVA Recommendation

Based on satellite imagery and AI analysis,
the proposed afforestation project is expected to:

- 🌳 Increase vegetation cover
- 🌍 Enhance carbon sequestration
- 💧 Protect soil resources
- 🌦 Improve climate resilience
- 🌱 Support sustainable environmental development

---

### توصية ENVA

يوصي النظام بتنفيذ برنامج التشجير المقترح
لتحسين الغطاء النباتي وخفض الانبعاثات
ودعم التنمية البيئية المستدامة.
"""
        )

    with right:

        st.metric(
            "Project Status",
            "READY"
        )

        st.metric(
            "AI Decision",
            "APPROVED"
        )

        st.metric(
            "Recommended Tree",
            str(recommended_tree)
        )

    st.markdown("---")

    # ======================================================
    # DOWNLOAD RESULTS
    # ======================================================

    st.subheader("📥 Download Results")

    col1, col2 = st.columns(2)

    with col1:

        csv = AFF_SUMMARY.to_csv(
            index=False
        ).encode("utf-8")

        st.download_button(
            label="⬇ Download Summary CSV",
            data=csv,
            file_name="ENVA_Afforestation_Summary.csv",
            mime="text/csv"
        )

    with col2:

        report = json.dumps(
            AFF_REPORT,
            indent=4,
            ensure_ascii=False
        )

        st.download_button(
            label="⬇ Download AI Report",
            data=report,
            file_name="ENVA_Afforestation_Report.json",
            mime="application/json"
        )

    st.markdown("---")

    st.success(
        """
### ✅ Smart Afforestation Module Completed Successfully

The AI analysis has generated afforestation recommendations,
estimated environmental benefits,
and project implementation indicators.

تم إنشاء جميع مؤشرات مشروع التشجير الذكي بنجاح،
وأصبحت النتائج جاهزة للتنزيل والاستخدام.
"""
    )

    st.caption(
        "Generated automatically by ENVA AI Smart Afforestation Engine."
    )
# ======================================================
# FUTURE EXPANSION — ENVA FUTURE VISION
# ======================================================

elif page == "🔮 Future Expansion":

    # ==================================================
    # PAGE INTRODUCTION
    # ==================================================

    st.title("🔮 ENVA Future Vision")

    st.subheader(
        "من نموذج أولي تجريبي مبسط إلى منظومة وطنية للذكاء البيئي"
    )

    st.markdown("""
    **From a Simple Prototype to a National Environmental
    Intelligence System**

    تمثل هذه الصفحة الرؤية المستقبلية لتطور ENVA.
    النسخة الحالية من المشروع هي نموذج أولي تجريبي مبسط
    لإثبات الفكرة الأساسية، بينما توضح هذه الصفحة كيف يمكن
    تطوير المنظومة مستقبلًا باستخدام تقنيات وبيانات أكثر تقدمًا.
    """)

    # ==================================================
    # PROTOTYPE NOTICE
    # ==================================================

    st.warning("""
    ⚠️ **Current Status — نموذج أولي تجريبي**

    النسخة الحالية من ENVA هي نموذج أولي مبسط جدًا
    تم تطويره لإثبات مفهوم دمج بيانات الأقمار الصناعية
    والتحليل البيئي والذكاء الاصطناعي ودعم اتخاذ القرار.

    **Future Vision**

    تمثل العناصر التالية مسار التطوير المستقبلي للمنظومة،
    وليست جميعها وظائف مطبقة بالكامل في النموذج الحالي.
    """)

    st.markdown("---")

    # ==================================================
    # ENVA — MORE THAN A PLATFORM
    # ==================================================

    st.header("🧠 ENVA — More Than a Platform")

    st.markdown("""
    **ENVA ليست مجرد منصة لعرض البيانات.**

    الرؤية المستقبلية هي تطوير ENVA إلى **منظومة ذكاء بيئي
    متكاملة** تستطيع جمع البيانات وتحليلها واكتشاف المخاطر
    والتنبؤ بها ثم تحويل نتائج التحليل إلى توصيات وقرارات
    قابلة للتنفيذ.
    """)

    st.markdown("### منظومة العمل المستقبلية")

    c1, c2, c3, c4 = st.columns(4)

    c1.info("""
    ### 🛰️ Data

    Satellite Data

    Environmental Data

    Ground Observations
    """)

    c2.info("""
    ### 🤖 Intelligence

    AI Models

    Computer Vision

    ENVA AI Agent
    """)

    c3.info("""
    ### 🚨 Prediction

    Risk Detection

    Forecasting

    Early Warning
    """)

    c4.info("""
    ### 🎯 Decision

    Recommendations

    Priority

    Government Action
    """)

    # ==================================================
    # FUTURE INTELLIGENCE CYCLE
    # ==================================================

    st.markdown("---")

    st.header("🔄 ENVA Future Intelligence Cycle")

    cycle = [
        ("🛰️", "Satellite Data", "بيانات الأقمار الصناعية"),
        ("🤖", "ENVA AI Agent", "وكيل الذكاء الاصطناعي"),
        ("🧠", "AI Analysis", "التحليل الذكي"),
        ("🌍", "Environmental Intelligence", "الذكاء البيئي"),
        ("🚨", "Early Warning", "الإنذار المبكر"),
        ("🎯", "Decision Support", "دعم القرار"),
        ("🏛️", "Government Action", "الإجراء الحكومي")
    ]

    for i, (icon, title, arabic) in enumerate(cycle):

        st.markdown(
            f"""
            <div style="
                background:linear-gradient(135deg,#071827,#102b3d);
                padding:18px;
                border-radius:16px;
                border:1px solid rgba(56,189,248,0.25);
                text-align:center;
                margin:8px 0;
            ">
                <div style="
                    font-size:28px;
                    font-weight:900;
                    color:#bae6fd;
                ">
                    {icon} {title}
                </div>

                <div style="
                    color:#cbd5e1;
                    font-size:15px;
                    margin-top:5px;
                ">
                    {arabic}
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

        if i < len(cycle) - 1:
            st.markdown(
                "<div style='text-align:center;font-size:25px;color:#86efac;'>↓</div>",
                unsafe_allow_html=True
            )

    # ==================================================
    # 3. ADVANCED SATELLITE INTELLIGENCE
    # ==================================================

    st.markdown("---")

    st.header("🛰️ Advanced Satellite Intelligence")

    st.subheader(
        "الذكاء الفضائي المتقدم"
    )

    st.write(
        "Future ENVA can evolve from basic satellite analysis "
        "into a continuous multi-source environmental intelligence system."
    )

    st.write(
        "يمكن تطوير ENVA مستقبلًا من تحليل صور الأقمار الصناعية "
        "إلى منظومة ذكاء فضائي مستمرة تعتمد على مصادر متعددة "
        "وتحليل التغيرات البيئية عبر الزمن."
    )

    # ==================================================
    # SATELLITE VISUAL
    # ==================================================

    st.markdown(
        """
        <div style="
            background:linear-gradient(135deg,#061923,#0b3034,#071923);
            padding:35px 20px;
            border-radius:25px;
            border:1px solid rgba(45,212,191,0.35);
            box-shadow:0 14px 40px rgba(0,0,0,0.35);
            text-align:center;
            margin:20px 0;
        ">

            <div style="
                font-size:30px;
                font-weight:900;
                color:#99f6e4;
                margin-bottom:10px;
            ">
                🛰️ Satellite Intelligence
            </div>

            <div style="
                color:#cbd5e1;
                font-size:16px;
                margin-bottom:25px;
            ">
                من البيانات الفضائية إلى الذكاء البيئي
            </div>

            <div style="
                display:flex;
                justify-content:center;
                align-items:center;
                gap:12px;
                flex-wrap:wrap;
            ">

                <div style="
                    padding:18px 22px;
                    border-radius:16px;
                    background:rgba(14,116,144,0.30);
                    color:#e0f2fe;
                    font-weight:800;
                ">
                    🛰️ Satellite Data
                    <br>
                    <small>البيانات الفضائية</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="
                    padding:18px 22px;
                    border-radius:16px;
                    background:rgba(37,99,235,0.25);
                    color:#dbeafe;
                    font-weight:800;
                ">
                    🔍 Change Detection
                    <br>
                    <small>اكتشاف التغيرات</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="
                    padding:18px 22px;
                    border-radius:16px;
                    background:rgba(124,58,237,0.25);
                    color:#ede9fe;
                    font-weight:800;
                ">
                    🧠 Intelligence
                    <br>
                    <small>الذكاء البيئي</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="
                    padding:18px 22px;
                    border-radius:16px;
                    background:rgba(22,163,74,0.25);
                    color:#dcfce7;
                    font-weight:800;
                ">
                    🎯 Decision
                    <br>
                    <small>دعم القرار</small>
                </div>

            </div>
        </div>
        """,
        unsafe_allow_html=True
    )

    s1, s2 = st.columns(2)

    with s1:

        st.markdown("### 🛰️ High-Resolution Satellite Data")

        st.write(
            "استخدام صور أقمار صناعية أعلى دقة للحصول على "
            "تفاصيل مكانية أكثر دقة."
        )

        st.markdown("""
        - Sentinel
        - Landsat
        - Commercial High-Resolution Imagery
        """)

    with s2:

        st.markdown("### 🔄 Continuous Monitoring")

        st.write(
            "متابعة التغيرات البيئية بصورة دورية بدل الاعتماد "
            "على تحليل صورة منفردة."
        )

        st.markdown("""
        - Historical Comparison
        - Time-Series Analysis
        - Change Detection
        """)

    st.markdown("### 🌍 Multi-Source Satellite Intelligence")

    m1, m2, m3 = st.columns(3)

    with m1:
        st.info("""
        🛰️ **Optical Imagery**

        تحليل الغطاء النباتي،
        استخدامات الأراضي،
        والمناطق العمرانية.
        """)

    with m2:
        st.info("""
        📡 **Radar Imagery**

        دعم الرصد في الظروف الجوية
        التي تحد من الاستفادة من
        الصور البصرية.
        """)

    with m3:
        st.info("""
        ⏱️ **Time-Series Data**

        مقارنة التغيرات البيئية
        عبر فترات زمنية متعددة.
        """)

    st.markdown("### 🔄 Future Satellite Analysis Workflow")

    flow1, flow2, flow3, flow4 = st.columns(4)

    with flow1:
        st.success("🛰️ Acquire\n\nجمع البيانات الفضائية")

    with flow2:
        st.success("🧹 Process\n\nمعالجة وتنقية البيانات")

    with flow3:
        st.success("🔍 Detect\n\nاكتشاف التغيرات")

    with flow4:
        st.success("🧠 Understand\n\nتحويلها إلى ذكاء بيئي")

    # ==================================================
    # 4. ADVANCED AI & PREDICTIVE ANALYTICS
    # ==================================================

    st.markdown("---")

    st.header("🤖 Advanced AI & Predictive Analytics")

    st.subheader(
        "الذكاء الاصطناعي والتحليلات التنبؤية"
    )

    st.write(
        "The future ENVA system is designed to move beyond "
        "describing environmental conditions toward predicting "
        "future risks and supporting proactive decisions."
    )

    st.write(
        "الرؤية المستقبلية لـ ENVA هي الانتقال من مجرد وصف "
        "الحالة البيئية إلى تحليلها والتنبؤ بالمخاطر المستقبلية "
        "ودعم اتخاذ إجراءات استباقية."
    )

    st.markdown(
        """
        <div style="
            background:linear-gradient(135deg,#071827,#102b3d,#071827);
            padding:32px 22px;
            border-radius:24px;
            border:1px solid rgba(56,189,248,0.30);
            box-shadow:0 12px 35px rgba(0,0,0,0.30);
            text-align:center;
            margin:20px 0;
        ">

            <div style="
                font-size:30px;
                font-weight:900;
                color:#bae6fd;
            ">
                🧠 ENVA AI Intelligence Engine
            </div>

            <div style="
                color:#cbd5e1;
                margin:10px 0 25px;
            ">
                العقل الذكي للتحليل والتنبؤ واتخاذ القرار
            </div>

            <div style="
                display:flex;
                justify-content:center;
                align-items:center;
                gap:12px;
                flex-wrap:wrap;
            ">

                <div style="padding:18px 22px;border-radius:16px;background:rgba(14,116,144,.30);color:#e0f2fe;font-weight:800;">
                    🛰️ Data
                    <br><small>البيانات</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="padding:18px 22px;border-radius:16px;background:rgba(37,99,235,.25);color:#dbeafe;font-weight:800;">
                    🤖 AI Models
                    <br><small>نماذج الذكاء الاصطناعي</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="padding:18px 22px;border-radius:16px;background:rgba(124,58,237,.25);color:#ede9fe;font-weight:800;">
                    🔮 Prediction
                    <br><small>التنبؤ</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="padding:18px 22px;border-radius:16px;background:rgba(22,163,74,.25);color:#dcfce7;font-weight:800;">
                    🎯 Decision
                    <br><small>القرار</small>
                </div>

            </div>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown("### 🧠 Future AI Capabilities")

    ai1, ai2, ai3 = st.columns(3)

    with ai1:
        st.info("🔍 **Computer Vision**\n\nتحليل الصور واكتشاف الأنماط والتغيرات البيئية.")

    with ai2:
        st.info("📈 **Predictive Analytics**\n\nتحليل السلاسل الزمنية والتنبؤ بالاتجاهات والمخاطر.")

    with ai3:
        st.info("🧠 **Deep Learning**\n\nنماذج أكثر تقدمًا لفهم الأنماط البيئية المعقدة.")

    st.markdown("### 🔄 ENVA AI Intelligence Cycle")

    p1, p2, p3, p4 = st.columns(4)

    with p1:
        st.success("🔍 Detect\n\nاكتشاف التغير أو الخطر")

    with p2:
        st.success("🧠 Analyze\n\nتحليل السبب والخصائص")

    with p3:
        st.success("🔮 Predict\n\nتوقع التطورات المستقبلية")

    with p4:
        st.success("🎯 Recommend\n\nاقتراح الإجراء المناسب")

    st.markdown("### 🔮 Future Prediction Areas")

    r1, r2 = st.columns(2)

    with r1:
        st.markdown("""
        **🌱 Environmental Prediction**

        - Vegetation Trends
        - Drought Risk
        - Land Degradation
        - Water Stress
        - Agricultural Change
        """)

    with r2:
        st.markdown("""
        **🚨 Risk Prediction**

        - Fire Probability
        - Flood Risk
        - Heatwave Risk
        - Pollution Risk
        - Environmental Hotspots
        """)

    st.header("🤖 ENVA AI Agent")

    st.write(
        "في الرؤية المستقبلية، يمكن تطوير ENVA AI Agent "
        "ليعمل كروبوت برمجي ذكي قادر على تشغيل عمليات التحليل "
        "وتجميع النتائج ومقارنتها ثم تقديم ملخص وتوصية قابلة للفهم."
    )

    agent1, agent2, agent3 = st.columns(3)

    with agent1:
        st.markdown("### 📥 Observe\n\nCollect environmental information\n\nجمع البيانات والمعلومات البيئية")

    with agent2:
        st.markdown("### 🧠 Reason\n\nAnalyze patterns and risks\n\nتحليل الأنماط والمخاطر")

    with agent3:
        st.markdown("### 🎯 Act\n\nRecommend a response\n\nاقتراح الإجراء المناسب")

    st.success("""
    🚀 **Future AI Vision**

    **Detect → Analyze → Predict → Recommend**

    **اكتشاف → تحليل → تنبؤ → توصية**

    الانتقال من Reactive Response إلى Proactive Environmental Management.
    """)

    # ==================================================
    # 5. NATIONAL EARLY WARNING SYSTEM
    # ==================================================

    st.markdown("---")

    st.header("🚨 National Early Warning System")

    st.subheader(
        "منظومة الإنذار البيئي المبكر"
    )

    st.write(
        "The future ENVA system can evolve from environmental "
        "monitoring into a predictive early warning system "
        "that detects emerging risks before they become critical."
    )

    st.write(
        "يمكن تطوير ENVA مستقبلًا من منظومة للرصد البيئي "
        "إلى نظام إنذار مبكر قادر على اكتشاف المخاطر المتوقعة "
        "والتنبيه إليها قبل تفاقمها."
    )

    st.markdown(
        """
        <div style="
            background:linear-gradient(135deg,#07151f,#132b35,#07151f);
            padding:32px 20px;
            border-radius:25px;
            border:1px solid rgba(248,113,113,.30);
            box-shadow:0 14px 40px rgba(0,0,0,.35);
            text-align:center;
            margin:20px 0;
        ">

            <div style="
                font-size:30px;
                font-weight:900;
                color:#fecaca;
            ">
                🚨 ENVA Early Warning Engine
            </div>

            <div style="color:#cbd5e1;margin:10px 0 28px;">
                محرك الإنذار المبكر للمخاطر البيئية
            </div>

            <div style="
                display:flex;
                justify-content:center;
                align-items:center;
                gap:12px;
                flex-wrap:wrap;
            ">

                <div style="padding:18px 20px;border-radius:16px;background:rgba(14,116,144,.28);color:#e0f2fe;font-weight:800;">
                    🛰️ Monitor
                    <br><small>رصد</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="padding:18px 20px;border-radius:16px;background:rgba(124,58,237,.25);color:#ede9fe;font-weight:800;">
                    🔍 Detect
                    <br><small>اكتشاف</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="padding:18px 20px;border-radius:16px;background:rgba(234,88,12,.25);color:#ffedd5;font-weight:800;">
                    🔮 Forecast
                    <br><small>توقع</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="padding:18px 20px;border-radius:16px;background:rgba(220,38,38,.25);color:#fee2e2;font-weight:800;">
                    🚨 Alert
                    <br><small>إنذار</small>
                </div>

                <div style="font-size:25px;color:#86efac;">→</div>

                <div style="padding:18px 20px;border-radius:16px;background:rgba(22,163,74,.25);color:#dcfce7;font-weight:800;">
                    🎯 Respond
                    <br><small>استجابة</small>
                </div>

            </div>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown("### ⚠️ Future Environmental Risk Categories")

    r1, r2, r3 = st.columns(3)

    with r1:
        st.error("🔥 **Fire Risk**\n\nالتنبؤ باحتمالات الحرائق ومناطق الخطر.")

    with r2:
        st.warning("🌵 **Drought Risk**\n\nرصد مؤشرات الجفاف والإجهاد المائي.")

    with r3:
        st.warning("🌊 **Flood Risk**\n\nالتنبؤ بالمناطق المعرضة لمخاطر السيول والفيضانات.")

    r4, r5, r6 = st.columns(3)

    with r4:
        st.warning("🌡️ **Heatwave Risk**\n\nاكتشاف والتنبؤ بموجات الحرارة الشديدة.")

    with r5:
        st.error("🌫️ **Pollution Risk**\n\nرصد المناطق التي قد تواجه ارتفاعًا في مستويات التلوث.")

    with r6:
        st.info("🌪️ **Extreme Weather**\n\nمتابعة مؤشرات الظواهر الجوية المتطرفة.")

    st.header("🔮 Risk Forecast")

    f1, f2, f3, f4 = st.columns(4)

    with f1:
        st.metric("🔥 Fire Probability", "—", "Future Model")

    with f2:
        st.metric("🌵 Drought Probability", "—", "Future Model")

    with f3:
        st.metric("🌊 Flood Probability", "—", "Future Model")

    with f4:
        st.metric("🌡️ Heatwave Probability", "—", "Future Model")

    st.caption(
        "Forecast values are part of the future system vision "
        "and are not operational predictions in the current prototype."
    )

    st.header("🎯 Risk Prioritization")

    p1, p2, p3 = st.columns(3)

    with p1:
        st.info("🟢 **Low Risk**\n\nRoutine monitoring")

    with p2:
        st.warning("🟡 **Moderate Risk**\n\nIncrease monitoring")

    with p3:
        st.error("🔴 **Critical Risk**\n\nImmediate response")

    st.header("🤖 AI Recommendation")

    a1, a2, a3 = st.columns(3)

    with a1:
        st.markdown("""
        ### 🔎 Risk Assessment

        **ما الذي يحدث؟**

        تحديد نوع الخطر وموقعه ومدى انتشاره.
        """)

    with a2:
        st.markdown("""
        ### 🎯 Priority

        **ما مدى خطورته؟**

        تحديد مستوى الأولوية ودرجة الاستجابة المطلوبة.
        """)

    with a3:
        st.markdown("""
        ### 🏛️ Recommended Action

        **ماذا يجب أن نفعل؟**

        اقتراح الإجراء المناسب للجهة المختصة.
        """)

    st.success("""
    🚨 **From Reactive to Proactive**

    **Detecting Problems After They Occur**

    إلى:

    **Predicting Risks Before They Escalate**
    """)

    # ==================================================
    # 6. IoT ENVIRONMENTAL SENSORS
    # ==================================================

    st.markdown("---")

    st.header("📡 IoT Environmental Sensors")

    st.subheader(
        "الاستشعار البيئي الميداني"
    )

    st.write(
        "Future ENVA can integrate real-time ground sensor data "
        "with satellite observations and AI models to create a "
        "continuous multi-source environmental monitoring system."
    )

    st.write(
        "يمكن ربط ENVA مستقبلًا بأجهزة استشعار ميدانية "
        "ترسل بيانات بيئية بصورة مستمرة، ليتم دمجها مع "
        "بيانات الأقمار الصناعية ونماذج الذكاء الاصطناعي."
    )

    st.markdown(
        """
        <div style="
            background:linear-gradient(135deg,#061923,#0b3034,#071923);
            padding:35px 20px;
            border-radius:25px;
            border:1px solid rgba(45,212,191,.35);
            box-shadow:0 14px 40px rgba(0,0,0,.35);
            text-align:center;
            margin:20px 0;
        ">

            <div style="
                font-size:30px;
                font-weight:900;
                color:#99f6e4;
            ">
                📡 ENVA Multi-Source Environmental Intelligence
            </div>

            <div style="color:#cbd5e1;margin:10px 0 28px;">
                دمج الرصد الفضائي مع الاستشعار الميداني والذكاء الاصطناعي
            </div>

            <div style="
                display:flex;
                justify-content:center;
                align-items:center;
                gap:12px;
                flex-wrap:wrap;
            ">

                <div style="padding:20px 24px;border-radius:18px;background:rgba(14,116,144,.28);color:#e0f2fe;font-weight:800;">
                    🛰️ Satellite Data
                    <br><small>بيانات الأقمار الصناعية</small>
                </div>

                <div style="font-size:25px;color:#5eead4;">+</div>

                <div style="padding:20px 24px;border-radius:18px;background:rgba(13,148,136,.25);color:#ccfbf1;font-weight:800;">
                    📡 IoT Sensors
                    <br><small>أجهزة الاستشعار</small>
                </div>

                <div style="font-size:25px;color:#5eead4;">+</div>

                <div style="padding:20px 24px;border-radius:18px;background:rgba(22,163,74,.25);color:#dcfce7;font-weight:800;">
                    🤖 AI
                    <br><small>الذكاء الاصطناعي</small>
                </div>

            </div>

            <div style="font-size:30px;color:#5eead4;margin:18px 0;">
                ↓
            </div>

            <div style="
                display:inline-block;
                padding:18px 32px;
                border-radius:18px;
                background:rgba(124,58,237,.22);
                color:#ede9fe;
                font-size:20px;
                font-weight:900;
            ">
                🌍 Integrated Environmental Intelligence
                <br><small>ذكاء بيئي متكامل</small>
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown("### 📊 Future Environmental Sensor Network")

    s1, s2, s3 = st.columns(3)

    with s1:
        st.info("""
        🌫️ **Air Quality**

        PM2.5  
        PM10  
        CO₂  
        NO₂  
        Other pollutants
        """)

    with s2:
        st.info("""
        🌡️ **Climate Sensors**

        Temperature  
        Humidity  
        Wind Speed  
        Solar Radiation
        """)

    with s3:
        st.info("""
        💧 **Water & Soil**

        Water Quality  
        Water Level  
        Soil Moisture  
        Soil Conditions
        """)

    st.markdown("---")

    st.markdown("### 🔄 Real-Time Environmental Data Flow")

    d1, d2, d3, d4 = st.columns(4)

    with d1:
        st.success("📡 Sensors\n\nCollect")

    with d2:
        st.success("☁️ Data Layer\n\nTransmit")

    with d3:
        st.success("🤖 ENVA AI\n\nAnalyze")

    with d4:
        st.success("🚨 Alert\n\nRespond")

    st.markdown("---")

    st.header("🎯 Future Sensor Use Cases")

    u1, u2 = st.columns(2)

    with u1:
        st.markdown("""
        ### 🌫️ Air Pollution Monitoring

        يمكن للحساسات الميدانية دعم ENVA في:

        - اكتشاف ارتفاع مستويات الملوثات.
        - مقارنة القياسات الأرضية بالبيانات الفضائية.
        - تحديد المناطق الأكثر تعرضًا للتلوث.
        - دعم منظومة Early Warning.
        """)

    with u2:
        st.markdown("""
        ### 💧 Water & Soil Monitoring

        يمكن استخدام البيانات الميدانية في:

        - متابعة جودة المياه.
        - قياس رطوبة التربة.
        - دعم تحليل الجفاف.
        - تحسين قرارات إدارة الموارد الطبيعية.
        """)

    st.markdown("---")

    st.header("🛰️ + 📡 Satellite–Ground Verification")

    v1, v2, v3 = st.columns(3)

    with v1:
        st.markdown("""
        **🛰️ Satellite Observation**

        What is detected from space?
        """)

    with v2:
        st.markdown("""
        **📡 Ground Measurement**

        What is measured on site?
        """)

    with v3:
        st.markdown("""
        **🧠 AI Validation**

        Do both sources agree?
        """)

    st.success("""
    🌍 **Future Value**

    **Satellite Data + Ground Sensors + AI**

    دمج الأقمار الصناعية مع أجهزة الاستشعار الميدانية
    سيجعل ENVA قادرة على بناء صورة بيئية أكثر شمولًا.
    """)

    # ==================================================
    # FUTURE VISION SUMMARY
    # ==================================================

    st.markdown("---")

    st.header("🌍 ENVA — National Environmental Intelligence")

    st.markdown("""
    ### **From Data → Intelligence → Prediction → Warning → Decision → Action**
    """)

    st.markdown("""
    **ENVA aims to evolve from a simplified experimental
    prototype into an integrated national environmental
    intelligence and decision-support system.**

    تهدف ENVA مستقبلًا إلى التطور من نموذج أولي تجريبي
    مبسط إلى منظومة وطنية متكاملة للذكاء البيئي ودعم
    اتخاذ القرار، تجمع بين بيانات الأقمار الصناعية،
    والذكاء الاصطناعي، والاستشعار الميداني، والتحليلات
    التنبؤية والإنذار المبكر.
    """)

    st.success(
        "🌱 ENVA Future Vision — Building Environmental Intelligence for Better Decisions"
    )

    st.caption(
        "Future Expansion — From Prototype → National Environmental Intelligence Ecosystem"
    )
